# Generated by Django 5.0.3 on 2024-03-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.IntegerField()),
                ('CustomerName', models.CharField(max_length=25)),
                ('ContactName', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=10)),
                ('PostalCode', models.IntegerField()),
                ('Country', models.CharField(max_length=200)),
            ],
        ),
    ]
