# Generated by Django 5.0.3 on 2024-03-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('date_of_publishing', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
