# Generated by Django 5.0.3 on 2024-03-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
