# Generated by Django 5.0.3 on 2024-03-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('BirthDate', models.DateField()),
                ('Photo', models.ImageField(blank=True, upload_to='photos')),
                ('Notes', models.TextField(blank=True)),
            ],
        ),
    ]
