# Generated by Django 5.0.3 on 2024-03-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0007_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Photo',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
