# Generated by Django 5.0.3 on 2024-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0008_remove_employee_photo_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('OrderDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderID', models.IntegerField()),
                ('ProductID', models.IntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
