# Generated by Django 5.0.3 on 2024-03-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0011_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('ShipperID', models.AutoField(primary_key=True, serialize=False)),
                ('ShipperName', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
    ]
