# Generated by Django 5.0.3 on 2024-03-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0013_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
