# Generated by Django 5.0.3 on 2024-03-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0015_remove_supplier_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
