# Generated by Django 5.0.3 on 2024-03-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0017_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Review', models.TextField(default='')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
