# Generated by Django 5.0.3 on 2024-03-25 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0018_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Date',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
