# Generated by Django 5.0.3 on 2024-03-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0019_remove_review_date_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.IntegerField(default=''),
        ),
    ]
